/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/schools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 학교 검색 */
        get: operations["searchSchools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 중식 조회 */
        get: operations["searchMeals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Calorie */
        Calorie: {
            /** Amount */
            amount: number;
            /**
             * Unit
             * @constant
             */
            unit: "kcal";
        };
        /** DateRange */
        DateRange: {
            /**
             * From
             * Format: date
             */
            from: string;
            /**
             * To
             * Format: date
             */
            to: string;
        };
        /** FieldError */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** IngredientOrigin */
        IngredientOrigin: {
            /** Ingredient */
            ingredient: string;
            /** Origin */
            origin: string;
        };
        /** Meal */
        Meal: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Dishes */
            dishes: string[];
            calorie: components["schemas"]["Calorie"] | null;
            /** Nutrition */
            nutrition: components["schemas"]["Nutrient"][];
            /** Origininfo */
            originInfo: components["schemas"]["IngredientOrigin"][];
            /** Servingcount */
            servingCount: number | null;
        };
        /** MealSearchResponse */
        MealSearchResponse: {
            school: components["schemas"]["SelectedSchool"];
            range: components["schemas"]["DateRange"];
            /**
             * Mealtype
             * @constant
             */
            mealType: "LUNCH";
            /** Items */
            items: components["schemas"]["Meal"][];
        };
        /** Nutrient */
        Nutrient: {
            /** Name */
            name: string;
            /** Amount */
            amount: number;
            /** Unit */
            unit: string;
        };
        /** Pagination */
        Pagination: {
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Totalcount */
            totalCount: number;
        };
        /** ProblemDetails */
        ProblemDetails: {
            /**
             * Type
             * Format: uri
             */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail: string;
            /** Instance */
            instance: string;
            /** Code */
            code: string;
            /** Errors */
            errors?: components["schemas"]["FieldError"][] | null;
            /** Traceid */
            traceId: string;
        };
        /** SchoolSearchResponse */
        SchoolSearchResponse: {
            /** Items */
            items: components["schemas"]["SchoolSummary"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** SchoolSummary */
        SchoolSummary: {
            /** Educationofficecode */
            educationOfficeCode: string;
            /** Educationofficename */
            educationOfficeName: string;
            /** Schoolcode */
            schoolCode: string;
            /** Name */
            name: string;
            /** Schooltype */
            schoolType: string;
            /** Region */
            region: string;
            /** Address */
            address: string | null;
        };
        /** SelectedSchool */
        SelectedSchool: {
            /** Educationofficecode */
            educationOfficeCode: string;
            /** Schoolcode */
            schoolCode: string;
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchSchools: {
        parameters: {
            query: {
                /** @description 학교 이름의 일부. 앞뒤 공백 제거 후 2~100자 */
                query: string;
                /** @description 페이지 번호 */
                page?: number;
                /** @description 페이지당 결과 수 */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolSearchResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    searchMeals: {
        parameters: {
            query: {
                /** @description NEIS 시도교육청 코드 */
                educationOfficeCode: string;
                /** @description NEIS 학교 행정표준코드 */
                schoolCode: string;
                /** @description 조회 시작일 */
                from: string;
                /** @description 조회 종료일 */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealSearchResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Gateway Timeout */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
